/**
 * lib/types.ts — Centralized type system
 *
 * Single source of truth for all shared TypeScript types across the backend.
 * Req: 13.1, 13.5 | Design §6
 *
 * NOTE: Prisma model type re-exports at the bottom of this file require
 * `npx prisma generate` to have been run first. Until then, importing
 * from `@prisma/client` will use the stub types shipped with the package.
 */

// ---------------------------------------------------------------------------
// Generic action result — discriminated union used by all Server Actions
// ---------------------------------------------------------------------------

export type ActionResult<T> =
  | { success: true; data: T }
  | { success: false; error: string };

// ---------------------------------------------------------------------------
// Domain-specific union types
// ---------------------------------------------------------------------------

/** Roles that exist in the `public.users` table and drive authorization. */
export type UserRole = "admin" | "bendahara" | "murid";

/** Payment lifecycle states for `dues_payments.status`. */
export type PaymentStatus = "pending" | "paid" | "overdue";

/** Attendance record states — must match the CHECK constraint in Postgres. */
export type AttendanceStatus = "HADIR" | "IZIN" | "SAKIT" | "ALFA";

/** Announcement visibility states. */
export type AnnouncementStatus = "draft" | "published";

// ---------------------------------------------------------------------------
// Interfaces
// ---------------------------------------------------------------------------

/**
 * Aggregated attendance statistics for a given date.
 * Returned by `getAttendanceStats()` in attendance.actions.ts.
 */
export interface AttendanceStats {
  /** Total number of students (users with role "murid"). */
  studentsCount: number;
  /** Number of students with status "HADIR" on the queried date. */
  presentCount: number;
  /** presentCount / studentsCount × 100, rounded to 2 decimal places. */
  attendanceRate: number;
}

/**
 * A single row from the `public.dues_summary` SQL view.
 * The view joins `dues_payments`, `users`, and `dues_periods`.
 */
export interface DuesSummaryRow {
  /** UUID — primary key of the `dues_payments` row. */
  id: string;
  /** UUID — references `users.id`. */
  student_id: string;
  /** Full name of the student. */
  name: string;
  /** Email address of the student. */
  email: string;
  /** UUID — references `dues_periods.id`. */
  period_id: string;
  /** Human-readable period label, e.g. "Agustus 2026". */
  period_name: string;
  /** Amount in Rupiah (integer). */
  amount: number;
  /** Current payment status. */
  status: PaymentStatus;
  /** Timestamp when payment was confirmed, or null if not yet paid. */
  paid_at: Date | null;
  /** Cloudinary secure URL of the payment proof image, or null if absent. */
  proof_image_url: string | null;
}

/**
 * Authenticated user data passed throughout the request lifecycle.
 * Built by `getCurrentUser()` in lib/actions/guards.ts.
 */
export interface CurrentUser {
  /** UUID from `auth.users.id` / `public.users.id`. */
  id: string;
  email: string;
  name: string;
  role: UserRole;
  /** Cloudinary avatar URL, or null if not set. */
  avatarUrl: string | null;
}

// ---------------------------------------------------------------------------
// Prisma model type re-exports
//
// These types are generated by `npx prisma generate` and live in
// `.prisma/client`. Run `prisma generate` before building the project.
// After generation, every model type becomes available via @prisma/client.
// ---------------------------------------------------------------------------

export type {
  User,
  DuesPeriod,
  DuesPayment,
  Announcement,
  Schedule,
  PhotoGallery,
  Photo,
  AuditLog,
  Attendance,
  Material,
  ForumPost,
  ForumComment,
} from "@/generated/prisma/client";
